name: Front Build and Deploy

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: pong42
  WORK_PATH: ./frontend
  RESOURCE_PATH: ./frontend/build
  CONSTFILE: ./src/constVariables.ts

on:
  push:
    branches: [ main-fe, dev-fe ] 
 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout release
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Build project
      run: |
        cd $WORK_PATH
        cat << EOF > $CONSTFILE
        export const serverUrl = '15.165.142.36:5500';
        export const apiKey = 'ebb3c5adb06b4dc2fa9b668ac36f3a3d799eaffde48dedec79af549e0197098f';
        export const OauthUrl = \`https://api.intra.42.fr/oauth/authorize?client_id=ebb3c5adb06b4dc2fa9b668ac36f3a3d799eaffde48dedec79af549e0197098f&redirect_uri=http%3A%2F%2Fpong42.link%2Fcallback&response_type=code\`;
        EOF
        echo
        cat $CONSTFILE
        echo
        yarn install
        yarn build

    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Deploy to S3
      run: aws s3 sync $RESOURCE_PATH s3://$S3_BUCKET_NAME
